# Generated by Django 5.2.4 on 2025-08-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_phone_number_user_phone_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
