# Generated by Django 5.2.4 on 2025-08-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turfs', '0004_turf_approval_status'),
        ('Users', '0003_rename_phone_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='Turfs.turf'),
        ),
    ]
