# Generated by Django 5.2.4 on 2025-07-21 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Turf Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price per Hour (e.g., 1000.00)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='turf_images/', verbose_name='Turf Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'TURF_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_turfs', to=settings.AUTH_USER_MODEL, verbose_name='Turf Owner')),
            ],
            options={
                'verbose_name': 'Turf',
                'verbose_name_plural': 'Turfs',
                'ordering': ['-created_at'],
            },
        ),
    ]
