# Generated by Django 5.2.4 on 2025-08-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turfs', '0002_amenity_remove_turf_location_turf_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='closing_time',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turf',
            name='opening_time',
            field=models.TimeField(default='23:00'),
            preserve_default=False,
        ),
    ]
