# Generated by Django 5.2.4 on 2025-08-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turfs', '0003_turf_closing_time_turf_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
