# Generated by Django 5.2.4 on 2025-07-21 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Booking Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(limit_choices_to={'user_type': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='player_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Booked By')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turf_bookings', to='turfs.turf', verbose_name='Turf Booked')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['booking_date', 'start_time'],
                'unique_together': {('turf', 'booking_date', 'start_time', 'end_time')},
            },
        ),
    ]
